/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package so.ifsc.View;

import so.ifsc.Client;
import so.ifsc.View.Unsubscribe;

/**
 *
 * @author Miguel
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    private final Client client;
    /**
     * Creates new form Menu
     */
    public Menu(Client client) {
        initComponents();
        this.client = client;
        clientName.setText(client.clientId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subscribeBtn = new javax.swing.JButton();
        publishBtn = new javax.swing.JButton();
        unsubscribeBtn = new javax.swing.JButton();
        disconnectBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        topicBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        clientName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subscribeBtn.setText("Subscribe");
        subscribeBtn.addActionListener(this::subscribeBtnActionPerformed);

        publishBtn.setText("Publish");
        publishBtn.addActionListener(this::publishBtnActionPerformed);

        unsubscribeBtn.setText("Unsubscribe");
        unsubscribeBtn.addActionListener(this::unsubscribeBtnActionPerformed);

        disconnectBtn.setText("Disconnect");
        disconnectBtn.addActionListener(this::disconnectBtnActionPerformed);

        jLabel1.setText("Menu");

        topicBtn.setText("Topicos");
        topicBtn.addActionListener(this::topicBtnActionPerformed);

        jLabel2.setText("Cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(topicBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(disconnectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(publishBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(subscribeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unsubscribeBtn)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clientName)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publishBtn)
                    .addComponent(subscribeBtn))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disconnectBtn)
                    .addComponent(unsubscribeBtn))
                .addGap(30, 30, 30)
                .addComponent(topicBtn)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clientName))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subscribeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribeBtnActionPerformed
        Subscribe subscribe = new Subscribe(client);
    
        // Avisa o cliente que esta é a tela de inscrição ativa no momento
        client.setSubscribeView(subscribe); 

        subscribe.setVisible(true);
    }//GEN-LAST:event_subscribeBtnActionPerformed

    private void publishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishBtnActionPerformed
        Publish publish = new Publish(client);

        client.setPublishView(publish);
        
        publish.setVisible(true);
    }//GEN-LAST:event_publishBtnActionPerformed

    private void topicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicBtnActionPerformed
        String topicName = javax.swing.JOptionPane.showInputDialog(
            this, 
            "Digite o nome do novo tópico:", 
            "Criar Novo Tópico", 
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        // 2. Valida se o usuário cancelou ou deixou o campo vazio
        if (topicName == null || topicName.trim().isEmpty()) {
            return; // Cancela a operação silenciosamente
        }

        topicName = topicName.trim();

        // 3. Reaproveita a estrutura da sua classe Message
        so.ifsc.Model.Message msg = new so.ifsc.Model.Message();
        msg.type = "SUBSCRIBE";
        msg.clientId = client.getClientId();
        msg.topic = topicName;
        msg.payload = null;
        msg.date = java.time.LocalDate.now().toString();
        msg.time = java.time.LocalTime.now().toString();

        // 4. Envia o JSON para o servidor através do Client
        client.send(msg);

        // 5. Dá um feedback visual para o usuário
        javax.swing.JOptionPane.showMessageDialog(
                this, 
                "Solicitação de criação do tópico '" + topicName + "' enviada com sucesso!", 
                "Sucesso", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_topicBtnActionPerformed

    private void disconnectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectBtnActionPerformed
        // 1. Pergunta ao usuário se ele realmente quer sair (Boa prática de UX)
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Deseja realmente se desconectar da aplicação?", 
                "Confirmar Saída", 
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return; // Se o usuário clicar em "Não", cancela a desconexão
        }

        try {
            // 2. Monta a mensagem estruturada exatamente como estava no seu Tx.java
            so.ifsc.Model.Message msg = new so.ifsc.Model.Message();
            msg.type = "DISCONNECT";
            msg.clientId = client.getClientId();
            msg.topic = null;
            msg.payload = null;
            msg.date = java.time.LocalDate.now().toString();
            msg.time = java.time.LocalTime.now().toString();

            // 3. Envia o aviso de desconexão para o servidor
            client.send(msg);

            // 4. Fecha a aplicação de forma limpa
            // Nota: Se a sua classe Client tiver um método para fechar o socket (ex: client.closeConnection()), chame-o aqui.

            javax.swing.JOptionPane.showMessageDialog(this, "Conexão encerrada com sucesso!", "Até logo", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Fecha todas as telas e encerra o processo Java
            System.exit(0); 

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Erro ao desconectar", ex);
            System.exit(1);
        }
    }//GEN-LAST:event_disconnectBtnActionPerformed

    private void unsubscribeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unsubscribeBtnActionPerformed
        Unsubscribe unsubscribe = new Unsubscribe(client);
    
        // Registra a tela ativa no cliente
        client.setUnsubscribeView(unsubscribe);

        unsubscribe.setVisible(true);
    }//GEN-LAST:event_unsubscribeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientName;
    private javax.swing.JButton disconnectBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton publishBtn;
    private javax.swing.JButton subscribeBtn;
    private javax.swing.JButton topicBtn;
    private javax.swing.JButton unsubscribeBtn;
    // End of variables declaration//GEN-END:variables
}
