/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package so.ifsc.View;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import so.ifsc.Client;
import so.ifsc.Model.Message;

/**
 *
 * @author Miguel
 */
public class Subscribe extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Subscribe.class.getName());
    private final Client client;
    /**
     * Creates new form Subscribe
     */
    public Subscribe(Client client) {
        initComponents();
        this.client = client;
        
//        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            client.setSubscribeView(null);
        }
        });
        requestAllTopics();
    }
    
    private void requestAllTopics() {
        Message msg = new Message();
        msg.type = "LIST_ALL_TOPICS"; 
        msg.clientId = client.getClientId();
        client.send(msg);
    }
    
    public void updateTopics(List<String> topicsList) {
        SwingUtilities.invokeLater(() -> {
            topics.removeAllItems();
            for (String t : topicsList) {
                topics.addItem(t);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topics = new javax.swing.JComboBox<>();
        subscribeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        topics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        topics.addActionListener(this::topicsActionPerformed);

        subscribeBtn.setText("Subscribe");
        subscribeBtn.addActionListener(this::subscribeBtnActionPerformed);

        jLabel1.setText("Tópicos disponíveis: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(subscribeBtn)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(topics, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(subscribeBtn)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subscribeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribeBtnActionPerformed
        if (topics.getSelectedItem() == null || topics.getSelectedItem().toString().equals("Carregando tópicos...")) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um tópico válido.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String selectedTopic = topics.getSelectedItem().toString();

        // Cria a mensagem de inscrição baseada no seu Tx original
        Message msg = new Message();
        msg.type = "SUBSCRIBE";
        msg.clientId = client.getClientId();
        msg.topic = selectedTopic;
        msg.payload = null;
        msg.date = java.time.LocalDate.now().toString();
        msg.time = java.time.LocalTime.now().toString();

        client.send(msg);

        JOptionPane.showMessageDialog(this, "Inscrição enviada para o tópico: " + selectedTopic, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        
        client.setSubscribeView(null); // Limpa o vínculo
        dispose(); // Fecha a tela após se inscrever
    }//GEN-LAST:event_subscribeBtnActionPerformed

    private void topicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton subscribeBtn;
    private javax.swing.JComboBox<String> topics;
    // End of variables declaration//GEN-END:variables
}
