/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package so.ifsc.View;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import so.ifsc.Client;
import so.ifsc.Model.Message;

/**
 *
 * @author Miguel
 */
public class Unsubscribe extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Unsubscribe.class.getName());
    private final Client client;

    /**
     * Creates new form Unsubscribe
     */
    public Unsubscribe(Client client) {
        initComponents();
        this.client = client;
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                client.setUnsubscribeView(null);
            }
        });
        
        requestMyTopics();
    }
    
    private void requestMyTopics() {
        Message msg = new Message();
        msg.type = "LIST_MY_TOPICS"; // Usa a lógica do seu Tx antigo
        msg.clientId = client.getClientId();
        client.send(msg);
    }
    
    public void updateTopics(List<String> topicsList) {
        SwingUtilities.invokeLater(() -> {
            topic.removeAllItems();
            
            if (topicsList == null || topicsList.isEmpty()) {
                topic.addItem("Nenhum tópico inscrito");
                unsubscribeBtn.setEnabled(false); // Desativa o botão se não houver tópicos
                return;
            }
            
            unsubscribeBtn.setEnabled(true);
            for (String t : topicsList) {
                topic.addItem(t);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topic = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        unsubscribeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        topic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        topic.addActionListener(this::topicActionPerformed);

        jLabel1.setText("Tópicos inscritos: ");

        unsubscribeBtn.setText("Unsubscribe");
        unsubscribeBtn.addActionListener(this::unsubscribeBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(unsubscribeBtn)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(unsubscribeBtn)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicActionPerformed

    private void unsubscribeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unsubscribeBtnActionPerformed
        String selectedTopic = (topic.getSelectedItem() != null) ? topic.getSelectedItem().toString() : "";
        
        if (selectedTopic.isEmpty() || selectedTopic.equals("Carregando seus tópicos...") || selectedTopic.equals("Nenhum tópico inscrito")) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um tópico válido.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Monta a mensagem de UNSUBSCRIBE igualzinho ao Tx.java original
        Message msg = new Message();
        msg.type = "UNSUBSCRIBE";
        msg.clientId = client.getClientId();
        msg.topic = selectedTopic;
        msg.payload = null;
        msg.date = java.time.LocalDate.now().toString();
        msg.time = java.time.LocalTime.now().toString();

        client.send(msg);

        JOptionPane.showMessageDialog(this, "Você saiu do tópico: " + selectedTopic, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        
        client.setUnsubscribeView(null); // Limpa o vínculo
        dispose(); // Fecha a janela após a requisição
    }//GEN-LAST:event_unsubscribeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Unsubscribe().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> topic;
    private javax.swing.JButton unsubscribeBtn;
    // End of variables declaration//GEN-END:variables
}
